---
apiVersion: v1
kind: Secret
metadata:
  name: rhdh-secrets
  namespace: demo-project
  labels:
    app.kubernetes.io/managed-by: argocd
type: Opaque
stringData:
  BACKEND_SECRET: N4KQcvTEIi6lAMGB5S0vHvBZdeAh789+J
  K8S_SA_TOKEN: eyJhbGciOiJSUzI1NiIsImtpZCI6ImVMSEZyN2Y1eHB4Ti1ncjNDYnV3R1l0ckFnOXZKLURsczgyT1NTZDdmemsifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJkZW1vLXByb2plY3QiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlY3JldC5uYW1lIjoicmhkaC1rOHMtc2EtdG9rZW4iLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoicmhkaC1rOHMtc2EiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiIwYzA2NjU2MS1kMDc1LTRhOTQtYjg2Yy03YzE5NWU4NDhiODgiLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6ZGVtby1wcm9qZWN0OnJoZGgtazhzLXNhIn0.hExLv5tJyyMgwZk4FgaYWBMgIixyraq-CVJJqdB4sscpeERcxwnF83RDa6K_2IiVEcfay6qjxEWDumPI-uO6bRfuYCvZbvHATfwQgwpz3lpv7jO-IIZ0Tbi7QXijqp5YQb8AEisqTuDCwrS_RxaGQrwuTBQMPlQ887V7Mv3G7SVakVgzbGQPuyo0TrDj7dyvBH8pEaSJexOb3iwmEktsuUBB-HsUNJeXlvU1mKUdTOrVaTXon-vMfCpK-C0gbAaoA2ZtfqoWlO8kgPpjFN2_dXJI1Zsd0cZn-hitaBfDGa3j61st8sE-HODZKoK6CEFU4wIH8mtDHi6L7Hx2Huei-zTr5iYH3qIjktWhYPW6geogRluu-e2mrDiRYWnbnJlR0FWrUrLR4rSx9jAc04FfrWMChXiBiGQEIa2_vU0Qpdc-cgjINTZGmbeNA9uHNGVza5TfPidpYEI8D47jWZQyqhNk4ITwLMBg7FdgkGQuUNzAxyDiF6hEcr4rH82a-2tprlC78ZpBiHOxgLLsG4mSV41tE5gJ71jtjYRINSbcNubydu7zVXDy74HJcT3TonV3k9nkeaxHpQUPZ9ImWN1k4hQFhd4HrXsGXH--lwppH4VJzPOIteZ-xWu2mcHpXFxRavegS2GxA34m3UuUd1D2uhUHp65rdMzMgeIYvJ3obqY
  GITHUB_TOKEN: <github_token>
